/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemprocess;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author Sazzad
 */
public class Alarm2 extends javax.swing.JFrame {

    /**
     * Creates new form Alarm2
     */
    public Alarm2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        hCombo = new javax.swing.JComboBox();
        mcombo = new javax.swing.JComboBox();
        ampmcombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jTextField1.setText("Alarm    :");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(70, 100, 90, 30);

        jButton1.setText("Alarm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 300, 160, 50);

        jLabel3.setText("HH");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 60, 30, 16);

        jLabel2.setText("MM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 60, 30, 16);

        jLabel4.setText("am/pm");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 60, 50, 16);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(119, 390, 160, 40);

        String[] hour = new String[12];
        for(int i=1; i<13; i++) hour[i-1] = i + "";
        hCombo.setModel(new javax.swing.DefaultComboBoxModel(hour));
        hCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hComboActionPerformed(evt);
            }
        });
        jPanel1.add(hCombo);
        hCombo.setBounds(190, 100, 31, 22);

        String[] mm = new String[60];
        for(int i=0; i<60; i++) mm[i] = i+"";
        mcombo.setModel(new javax.swing.DefaultComboBoxModel(mm));
        mcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcomboActionPerformed(evt);
            }
        });
        jPanel1.add(mcombo);
        mcombo.setBounds(240, 100, 31, 22);

        ampmcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AM", "PM"}));
        ampmcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ampmcomboActionPerformed(evt);
            }
        });
        jPanel1.add(ampmcombo);
        ampmcombo.setBounds(290, 100, 31, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\java fx practice\\SystemProcess\\hj.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 610, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String hh =(String) hCombo.getSelectedItem();
        String mm =(String) mcombo.getSelectedItem();
        String offset =(String) ampmcombo.getSelectedItem();
        int off =-1;
        if(offset.contains("AM")) off =0;
        else off = 1;
        int hour = Integer.parseInt(hh)+12*off;
        
        String time = hour+":"+ mm;
        
        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {

            @Override
            public void run() {
                DateFormat df = new SimpleDateFormat("HH:mm");
                Date date = new Date();
                if(time.equals(df.format(date)))
                {
                    JOptionPane.showMessageDialog(null, "My Goodness, this is so concise");
                }
            }
        }, 0, 1000);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void hComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hComboActionPerformed

    private void mcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mcomboActionPerformed

    private void ampmcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ampmcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ampmcomboActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Welcomepage2 welcome2 = new Welcomepage2();
        welcome2.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alarm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alarm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alarm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alarm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alarm2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ampmcombo;
    private javax.swing.JComboBox hCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox mcombo;
    // End of variables declaration//GEN-END:variables
}
